export const GET_STATESPRODUCTS_SUCCESS = 'GET_STATESPRODUCTS_SUCCESS';
export const GET_STATESPRODUCTS_FAIL = 'GET_STATESPRODUCTS_FAIL';

export const GET_STATEPRODUCT_DETAILS_REQUEST = 'GET_STATEPRODUCT_DETAILS_REQUEST';
export const GET_STATEPRODUCT_DETAILS_SUCCESS = 'GET_STATEPRODUCT_DETAILS_SUCCESS';
export const GET_STATEPRODUCT_DETAILS_FAIL = 'GET_STATEPRODUCT_DETAILS_FAIL';
export const GET_STATEPRODUCT_DETAILS_RESET = 'GET_STATEPRODUCT_DETAILS_RESET';
