export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAIL = 'GET_STATES_FAIL';

export const GET_STATE_DETAILS_REQUEST = 'GET_STATE_DETAILS_REQUEST';
export const GET_STATE_DETAILS_SUCCESS = 'GET_STATE_DETAILS_SUCCESS';
export const GET_STATE_DETAILS_FAIL = 'GET_STATE_DETAILS_FAIL';
export const GET_STATE_DETAILS_RESET = 'GET_STATE_DETAILS_RESET';
    